#
## ######################################################################################
##
##   environment.yml
##
##   Defining conda/mamba software dependencies to run BScBI-CG practical exercises.
##
## ######################################################################################
##
##                 CopyLeft 2025 (CC:BY-NC-SA) --- Josep F Abril
##
##   This file should be considered under the Creative Commons BY-NC-SA License
##   (Attribution-Noncommercial-ShareAlike). The material is provided "AS IS", 
##   mainly for teaching purposes, and is distributed in the hope that it will
##   be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
##   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##
## ######################################################################################
#
# To install software for the exercise use the following command:
#
#    conda env create --file environment.yml
# 
# then run the command below to activate the conda environment:
#
#    conda activate BScBI-CG2526_exercises
#
name: BScBI-CG2526_exercises
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - htop
  - dnachun::neofetch
  - vim
  - emacs
  - gawk
  - perl
  - python
  - biopython
  - wget
  - curl
  - gzip
  - r-ggplot2
  ### you can try those at your own risk
  # - texlive-core
  # - pdflatex
  - pandoc
  - pandocfilters
